import FirebaseFirestore

/// Data Transfer Object representing an invitation to share a list
/// This struct maps directly to the Firestore document structure
struct InvitationDTO: Identifiable, Codable, Hashable {
    /// The unique identifier of the invitation, automatically generated by Firestore
    @DocumentID var id: String?
    /// The name of the user who sent the invitation
    let ownerName: String
    /// The email of the user who sent the invitation
    let ownerEmail: String
    /// The ID of the list being shared
    let listId: String
    /// The name of the list being shared
    let listName: String
    /// The ID of the user being invited
    let invitedId: String
    /// The index position of the invitation in the list
    let index: Int
}
