import FirebaseFirestore

/// Data Transfer Object representing a todo item
/// This struct maps directly to the Firestore document structure
public struct ItemDTO: Identifiable, Codable, Hashable {
    /// The unique identifier of the item, automatically generated by Firestore
    @DocumentID public var id: String?
    /// The name or description of the todo item
    let name: String
    /// Flag indicating whether the item is completed
    var done: Bool
    /// The index position of the item in the list
    var index: Int
}
