import FirebaseFirestore

/// Data Transfer Object representing a todo list
/// This struct maps directly to the Firestore document structure
struct ListDTO: Identifiable, Codable, Hashable {
    /// The unique identifier of the list, automatically generated by Firestore
    @DocumentID var id: String?
    /// The name of the todo list
    let name: String
    /// Flag indicating whether all items in the list are completed
    let done: Bool
    /// Array of user IDs who have access to this list
    var uid: [String]
    /// The index position of the list in the user's lists
    var index: Int
}
