import FirebaseFirestore

/// Data Transfer Object representing a user
/// This struct maps directly to the Firestore document structure
struct UserDTO: Identifiable, Codable, Hashable {
    /// The unique identifier of the user document, automatically generated by Firestore
    @DocumentID var id: String?
    /// The unique identifier of the user in the authentication system
    var uid: String
    /// The user's email address, if available
    var email: String?
    /// The user's display name, if available
    var displayName: String?
    /// URL to the user's profile photo, if available
    var photoUrl: String?
    /// The authentication provider used by the user (e.g., "google", "apple")
    var provider: String
}
