name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Se activa cuando subes algo a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create config.js from Secret
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > Web/public/config.js

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./Web # Aquí le decimos que tu proyecto está en la carpeta Web